// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagementAPI.Data;

#nullable disable

namespace TaskManagementAPI.Migrations
{
    [DbContext(typeof(ProjectTaskDbContext))]
    partial class ProjectTaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagementAPI.Model.ProjectMember", b =>
                {
                    b.Property<int>("ProjectMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectMemberId"));

                    b.Property<string>("MemberRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProjectMemberId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMembers");

                    b.HasData(
                        new
                        {
                            ProjectMemberId = 1,
                            MemberRole = "Project Manager",
                            ProjectId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ProjectMemberId = 2,
                            MemberRole = "Backend Developer",
                            ProjectId = 1,
                            UserId = 2
                        },
                        new
                        {
                            ProjectMemberId = 3,
                            MemberRole = "Technical Lead",
                            ProjectId = 2,
                            UserId = 2
                        },
                        new
                        {
                            ProjectMemberId = 4,
                            MemberRole = "QA/Tester",
                            ProjectId = 2,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("TaskManagementAPI.Model.ProjectObj", b =>
                {
                    b.Property<int>("ProjectObjId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectObjId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ProjectObjId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectObjId = 1,
                            IsDeleted = false,
                            ProjectDescription = "Làm trang web bán hàng cho đối tác",
                            ProjectName = "Dự án Website E-commerce",
                            StartDate = new DateTime(2026, 2, 13, 4, 19, 57, 285, DateTimeKind.Utc).AddTicks(3970),
                            Status = 1
                        },
                        new
                        {
                            ProjectObjId = 2,
                            IsDeleted = false,
                            ProjectDescription = "App quản lý nhân sự",
                            ProjectName = "Dự án Mobile App React Native",
                            StartDate = new DateTime(2026, 3, 25, 4, 19, 57, 285, DateTimeKind.Utc).AddTicks(3976),
                            Status = 0
                        });
                });

            modelBuilder.Entity("TaskManagementAPI.Model.TaskAssignment", b =>
                {
                    b.Property<int>("TaskAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskAssignmentId"));

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TaskAssignmentId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskAssignments");

                    b.HasData(
                        new
                        {
                            TaskAssignmentId = 1,
                            TaskId = 1,
                            UserId = 1
                        },
                        new
                        {
                            TaskAssignmentId = 2,
                            TaskId = 2,
                            UserId = 2
                        },
                        new
                        {
                            TaskAssignmentId = 3,
                            TaskId = 3,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TaskManagementAPI.Model.TaskObj", b =>
                {
                    b.Property<int>("TaskObjId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskObjId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskObjId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskObjId = 1,
                            CreatedAt = new DateTime(2026, 2, 15, 4, 19, 57, 285, DateTimeKind.Utc).AddTicks(4035),
                            DueDate = new DateTime(2026, 2, 23, 4, 19, 57, 285, DateTimeKind.Utc).AddTicks(4035),
                            IsCompleted = true,
                            ProjectId = 1,
                            TaskDescription = "Vẽ sơ đồ ERD và viết script SQL",
                            TaskName = "Thiết kế Database"
                        },
                        new
                        {
                            TaskObjId = 2,
                            CreatedAt = new DateTime(2026, 2, 24, 4, 19, 57, 285, DateTimeKind.Utc).AddTicks(4036),
                            DueDate = new DateTime(2026, 3, 20, 4, 19, 57, 285, DateTimeKind.Utc).AddTicks(4037),
                            IsCompleted = false,
                            ProjectId = 1,
                            TaskDescription = "Sử dụng JWT để làm tính năng Authentication",
                            TaskName = "Code API Đăng nhập"
                        },
                        new
                        {
                            TaskObjId = 3,
                            CreatedAt = new DateTime(2026, 3, 15, 4, 19, 57, 285, DateTimeKind.Utc).AddTicks(4037),
                            DueDate = new DateTime(2026, 3, 27, 4, 19, 57, 285, DateTimeKind.Utc).AddTicks(4038),
                            IsCompleted = false,
                            ProjectId = 2,
                            TaskDescription = "Cài đặt Android Studio và Xcode",
                            TaskName = "Setup môi trường Mobile"
                        });
                });

            modelBuilder.Entity("TaskManagementAPI.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            UserName = "Nguyễn Văn A (Manager)"
                        },
                        new
                        {
                            UserId = 2,
                            UserName = "Trần Thị B (Developer)"
                        },
                        new
                        {
                            UserId = 3,
                            UserName = "Lê Văn C (Tester)"
                        });
                });

            modelBuilder.Entity("TaskManagementAPI.Model.ProjectMember", b =>
                {
                    b.HasOne("TaskManagementAPI.Model.ProjectObj", "project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagementAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("project");
                });

            modelBuilder.Entity("TaskManagementAPI.Model.TaskAssignment", b =>
                {
                    b.HasOne("TaskManagementAPI.Model.TaskObj", "task")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagementAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("task");
                });

            modelBuilder.Entity("TaskManagementAPI.Model.TaskObj", b =>
                {
                    b.HasOne("TaskManagementAPI.Model.ProjectObj", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskManagementAPI.Model.ProjectObj", b =>
                {
                    b.Navigation("ProjectMembers");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskManagementAPI.Model.TaskObj", b =>
                {
                    b.Navigation("TaskAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
